import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

//Skrifttyper
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App", // Titlen på selve siden. Kan ses i browser tabben.
  description: "Generated by create next app",
};

//Skriftyperne skal sættes ind på denne måde i body tagget:
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
