import { Poppins } from "next/font/google";
import "./globals.css";
import MainHeader from "./components/layouts/header/MainHeader";

// Typhography:

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Iwatch Landing Page", // Titlen på selve siden. Kan ses i browser tabben.
  description: "Generated by create next app",
};

//Skriftyperne skal sættes ind på denne måde i body tagget:
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
